djangocrud/urls.py
from django.contrib import admin
from django.urls import include, path
from tasks import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'libreria'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks_completed/', views.tasks_completed, name='tasks_completed'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('libreria/', include('libreria.urls', namespace='libreria')),
]
# Configuración para servir archivos estáticos y de medios en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libreria/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static

app_name = 'libreria'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('libros/', views.libros, name='libros'),
    path('libros/crear/', views.crear, name='crear'),
    path('libros/editar/', views.editar, name='editar'),
    path('libros/<int:libro_id>/descargar-pdf/', views.descargar_pdf, name='descargar_pdf'),
    path('libros/eliminar/<int:id>',views.eliminar, name='eliminar'),
    path('libros/editar/<int:id>',views.editar, name='editar'),
]
# Configuración para servir archivos estáticos y de medios en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libreria/models.py
import os
from django.db import models

# Create your models here.
class Libro(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=100, verbose_name='Titulo')
    imagen = models.ImageField(upload_to='libros/imagenes/', verbose_name='Imagen', null=True)
    pdf = models.FileField(upload_to='pdfs/', verbose_name='PDF', null=True)
    descripcion = models.TextField(verbose_name='Descripcion', null=True)
    
    def __str__(self):
        fila = "Titulo: " + self.titulo + " - " + "Descripcion: " + self.descripcion
        return fila
    
    def delete(self, using=None, keep_parents=False):
        # Eliminar la imagen
        if self.imagen:
            path = self.imagen.path
            if os.path.exists(path):
                os.remove(path)

        # Eliminar el archivo PDF
        if self.pdf:
            path = self.pdf.path
            if os.path.exists(path):
                os.remove(path)

        super().delete(using=using, keep_parents=keep_parents)

libreria/forms.py
from django import forms
from .models import Libro

class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = '__all__'

libreria/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Libro
from .forms import LibroForm

from django.http import FileResponse
from libreria import models
# Create your views here.

def inicio(request):
    return render(request, 'paginas/inicio.html')

def nosotros(request):
    return render(request, 'paginas/nosotros.html')

def libros(request):
    libros = Libro.objects.all()
    return render(request, 'libros/index.html', {'libros': libros})

def crear(request):
    formulario = LibroForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('/libreria/libros/')
    return render(request, 'libros/crear.html', {'formulario': formulario})

def editar(request, id):
    libro = Libro.objects.get(id=id)
    formulario = LibroForm(request.POST or None, request.FILES or None, instance=libro)
    if formulario.is_valid() and request.method == 'POST':
        formulario.save()
        return redirect('/libreria/libros/')
    return render(request, 'libros/editar.html', {'formulario': formulario})

def descargar_pdf(request, libro_id):
    libro = get_object_or_404(Libro, id=libro_id)

    # Obtener la ruta del archivo PDF
    ruta_pdf = libro.pdf.path

    # Abrir el archivo PDF en modo binario
    with open(ruta_pdf, 'rb') as archivo_pdf:
        # Crear una respuesta de descarga del archivo
        response = FileResponse(archivo_pdf)
        # Establecer el encabezado para la descarga
        response['Content-Disposition'] = f'attachment; filename="{libro.pdf.name}"'
        return response
    
def eliminar(request, id):
    libro = Libro.objects.get(id=id)
    libro.delete()
    return redirect('/libreria/libros/')

libreria/templates/paginas/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>{% block titulo %}  {% endblock %}</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>

<body>

    <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="nav navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'libreria:inicio' %}" aria-current="page">Inicio </a>
            <a class="nav-item nav-link active" href="{% url 'libreria:libros' %}" aria-current="page">Libros </a>
            <a class="nav-item nav-link active" href="{% url 'tasks' %}" aria-current="page">Tasks</a>
            <a class="nav-item nav-link active" href="{% url 'libreria:nosotros' %}" aria-current="page">Nosotros </a>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-12">
              <br/>
                {% block contenido %}  {% endblock  %}
            </div>
        </div>
    </div>

  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>

libreria/templates/paginas/inicio.html
{% extends 'paginas/base.html' %}

{% block titulo %} Libreria {% endblock %}

{% block contenido %}

<div class="jumbotron">
    <h1 class="display-3">Bienvenido a la libreria</h1>
    <p class="lead">Empieza a ingresar libros</p>
    <hr class="my-2">
    <p class="lead">
    </p>
</div>

{% endblock  %}

libreria/templates/paginas/nosotros.html
{% extends 'paginas/base.html' %}

{% block titulo %} Nosotros {% endblock %}

{% block contenido %}
Desarrolladores:
<br/>
CRUZ SANCHEZ ANTONIO ISAI
<br/>
DE REGINO MAYA JAVIER
<br/>
MAYORAL LUNA ALEJANDRO 
{% endblock  %}