djangocrud/urls.py
from django.contrib import admin
from django.urls import include, path
from tasks import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'libreria'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks_completed/', views.tasks_completed, name='tasks_completed'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('libreria/', include('libreria.urls', namespace='libreria')),
]
# Configuración para servir archivos estáticos y de medios en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libreria/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static

app_name = 'libreria'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('libros/', views.libros, name='libros'),
    path('libros/crear/', views.crear, name='crear'),
    path('libros/editar/', views.editar, name='editar'),
    path('libros/<int:libro_id>/descargar-pdf/', views.descargar_pdf, name='descargar_pdf'),
    path('libros/eliminar/<int:id>',views.eliminar, name='eliminar'),
    path('libros/editar/<int:id>',views.editar, name='editar'),
]
# Configuración para servir archivos estáticos y de medios en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libreria/models.py
import os
from django.db import models

# Create your models here.
class Libro(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=100, verbose_name='Titulo')
    imagen = models.ImageField(upload_to='libros/imagenes/', verbose_name='Imagen', null=True)
    pdf = models.FileField(upload_to='pdfs/', verbose_name='PDF', null=True)
    descripcion = models.TextField(verbose_name='Descripcion', null=True)
    
    def __str__(self):
        fila = "Titulo: " + self.titulo + " - " + "Descripcion: " + self.descripcion
        return fila
    
    def delete(self, using=None, keep_parents=False):
        # Eliminar la imagen
        if self.imagen:
            path = self.imagen.path
            if os.path.exists(path):
                os.remove(path)

        # Eliminar el archivo PDF
        if self.pdf:
            path = self.pdf.path
            if os.path.exists(path):
                os.remove(path)

        super().delete(using=using, keep_parents=keep_parents)

libreria/forms.py
from django import forms
from .models import Libro

class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = '__all__'

libreria/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Libro
from .forms import LibroForm

from django.http import FileResponse
from libreria import models
# Create your views here.

def inicio(request):
    return render(request, 'paginas/inicio.html')

def nosotros(request):
    return render(request, 'paginas/nosotros.html')

def libros(request):
    libros = Libro.objects.all()
    return render(request, 'libros/index.html', {'libros': libros})

def crear(request):
    formulario = LibroForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('/libreria/libros/')
    return render(request, 'libros/crear.html', {'formulario': formulario})

def editar(request, id):
    libro = Libro.objects.get(id=id)
    formulario = LibroForm(request.POST or None, request.FILES or None, instance=libro)
    if formulario.is_valid() and request.method == 'POST':
        formulario.save()
        return redirect('/libreria/libros/')
    return render(request, 'libros/editar.html', {'formulario': formulario})

def descargar_pdf(request, libro_id):
    libro = get_object_or_404(Libro, id=libro_id)

    # Obtener la ruta del archivo PDF
    ruta_pdf = libro.pdf.path

    # Abrir el archivo PDF en modo binario
    with open(ruta_pdf, 'rb') as archivo_pdf:
        # Crear una respuesta de descarga del archivo
        response = FileResponse(archivo_pdf)
        # Establecer el encabezado para la descarga
        response['Content-Disposition'] = f'attachment; filename="{libro.pdf.name}"'
        return response
    
def eliminar(request, id):
    libro = Libro.objects.get(id=id)
    libro.delete()
    return redirect('/libreria/libros/')

libreria/templates/libros/crear.html
{% extends 'paginas/base.html' %}

{% block titulo %} Agregar {% endblock %}

{% block contenido %}
<div class="card">
    <div class="card-header">
        Crear Nuevo
    </div>
    <div class="card-body">
        <h4 class="card-title">Datos del libro</h4>
        {% include 'libros/form.html' %}
    </div>
    <div class="card-footer text-muted">
    </div>
</div>
{% endblock  %}

libreria/templates/libros/editar.html
{% extends 'paginas/base.html' %}

{% block titulo %} Editar {% endblock %}

{% block contenido %}
<div class="card">
    <div class="card-header">
        Editar libros
    </div>
    <div class="card-body">
        <h4 class="card-title">Datos del libro</h4>
        {% include 'libros/form.html' %}
    </div>
    <div class="card-footer text-muted">
    </div>
</div>
{% endblock  %}

libreria/templates/libros/form.html
{% load static %}
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {% for campo in formulario %}
    <div class="mb-3">
      <label for="" class="form-label">{{ campo.label }}:</label>
      {% if campo.field.widget.input_type == 'file' and campo.value %}
      <br/>
      <img src="{{MEDIA_URL}}/imagenes/{{campo.value}}" width="100" alt="" srcset="">
      {% endif %}
      {% if libro.pdf %}
        <a href="{{ libro.pdf.url }}" target="_blank">
            <img src="{% static 'static/icons/pdf.png' %}" width="100" />
        </a>
      {% endif %}
      <input
      type="{{ campo.field.widget.input_type }}"
      class="form-control"
      name="{{ campo.name }}"
      id=""
      aria-describedby="helpId"
      placeholder="{{ campo.label }}"
      value="{{ campo.value | default:'' }}" />
    </div>
    <div class="col-12 help-text">{{ campo.errors }}</div>
  {% endfor %}
<input name="" id="" class="btn btn-success" type="submit" value="Enviar">
<a name="" id="" class="btn btn-primary" href="{% url 'libreria:libros' %}" role="button">Cancelar</a>
</form>

libreria/templates/libros/index.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block titulo %} Libreria {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">
        <a name="" id="" class="btn btn-success" href="{% url 'libreria:crear' %}" role="button">Agregar Libro</a>
    </div>
    <div class="card-body">
        <h4 class="card-title">Libros</h4>
        <div class="table-responsive">
            <table class="table table">
                <thead>
                    
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Titulo</th>
                        <th scope="col">Imagen</th>
                        <th scope="col">PDF</th>
                        <th scope="col">Descripcion</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for libro in libros %}
                    <tr class="">
                        <td>{{ libro.id }}</td>
                        <td>{{ libro.titulo }}</td>
                        <td>
                            <img src="{{ libro.imagen.url }}" height="100" />
                        </td>
                        <td>
                            <a href="{{ libro.pdf.url }}" target="_blank">
                                <img src="{% static 'icons/pdf.png' %}" height="50" />
                              </a>
                        </td>
                        <td>{{ libro.descripcion }}</td>
                        <td>
                            <a name="" id="" class="btn btn-info" href="{% url 'libreria:editar' libro.id %}" role="button">Editar</a>
                            |
                            <a name="" id="" class="btn btn-danger" href="{% url 'libreria:eliminar' libro.id %}" role="button">Borrar</a>
                            |
                            <a name="" id="" class="btn btn-success" href="{{ libro.pdf.url }}" download="{{ libro.pdf.name }}" role="button">Descargar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock  %}